FROM python:3.11-slim

WORKDIR /app

# Copy requirements và cài dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY producer.py .
COPY .env .

# Chạy producer
CMD ["python", "producer.py"]
