FROM python:3.11-slim

WORKDIR /app

# Copy requirements và cài dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY consumer_database.py .
COPY .env .

# Chạy consumer
CMD ["python", "consumer_database.py"]
